spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

address:
  service:
    url: http://localhost:8082/addresses
